Fix entry points data generation
aiidateam/aiida-registry pull request #239
Opened 2023-05-23 21:49 UTC by AhmedBasem20

The issue is that `get_entry_point_names()` function return additional entry points names other than the current plugin entrypoints.
Example:
![image](https://github.com/aiidateam/aiida-registry/assets/62952819/9a9e9b17-087b-4499-bb69-b27b1311b2f7)
This should only be:
```
{
    "aiida.calculations": [
        "abinit"
    ],
    "aiida.workflows": [
        "abinit.base"
    ]
}
```
My solution is to pass the plugin entry points to the `analyze_entrypoints` module as a click option, and then use it to filter out the current plugin entry points from `get_entry_point_names()` results.

2023-05-26 10:30 UTC, ltalirz reviewed
thanks for the PR @AhmedBasem20 !

I see your solution but it seems a bit more complex to me than needed.

I first wanted to understand why the problem you noticed exists and, to be honest, I still don't quite understand how it arises.

Looking at the original code, I would expect each plugin install to occur in a separate docker container, so I would expect the return value of one run of `test_install_one_docker` to be entirely independent of the previous one.

I suspect it somehow happens through files being written to the shared working directory - can you please check this by running the workflow locally?

If that is the case, then the "fix" is much easier - simply make sure to clean up these temporary files before running the next container.

2023-05-26 10:30 UTC, ltalirz commented on aiida_registry/test_install.py
> +        results = test_install_one_docker(container_image, plugin)
is this going to try to install all of the plugins again?

2023-06-04 19:39 UTC, ltalirz requested changes
Thanks @ahmedbasem20 !

The direction is good, but I think there may be an easier way to achieve this

2023-06-04 19:39 UTC, ltalirz commented on .github/workflows/ci.yml
> +    - name: Generate entrypoints data
I suggest you simply modify the previous step instead.
I see below that you are installing all the plugins again here (which is very slow) - we should only do this once

2023-06-30 13:13 UTC, ltalirz reviewed
thank you @AhmedBasem20 , 

the changes you implemented look good to me.

only a few nitpicks left

2023-06-30 13:13 UTC, ltalirz commented on aiida_registry/test_install.py
> +    Extract entry points that belongs to the plugin,
```suggestion
    Extract entry points that belong to the plugin,
```

2023-06-30 13:13 UTC, ltalirz commented on aiida_registry/test_install.py
> +
If I understand correctly, here you are first building up the list of eps, then a list of keys to delete, then delete the keys

how about just _taking_ the entry points you want?

the code below is untested and likely not correct (I don't fully understand the structure of the current dictionaries), but it points in the direction
```
process_metadata = {}
for group_label, group_val in ENTRY_POINT_GROUPS:
  process_metadata[group_label]={}
  for ep_label, _ in process_metadata[group_label].items():
    process_metadata[group_label][ep_label] = group_val[ep_label]
```

2023-06-30 13:13 UTC, ltalirz commented on aiida_registry/test_install.py
> +                        data[_k]["entry_points"][ep_group][key] = process_metadata[
looks to me like `_k` is being used and should no longer start with an underscore (perhaps `plugin_name` or something)

2023-07-21 14:37 UTC, unkcpz commented
replaced by https://github.com/aiidateam/aiida-registry/pull/245

2023-07-21 14:37 UTC, closed without merging